services:
  - type: web
    name: eticketing-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: eticketing-db
          property: connectionString

databases:
  - name: eticketing-db
    databaseName: eticketing
    user: eticketing_user
